### Classification
1. Logistic regression
2. Decision Tree Classifier
3. Random Forest Classifier
4. XGB Classifier
5. AdaBoost Classifier
6. Catboost Classifier
7. K-Neighbor Classifier
8. Support Vector Classifier
9. Bernoulli Naive Bayes
10. Multinomial Naive Bayes
11. Bagging Classifier
12. Stacking Classifier

### Evaluation Metrics For Classification
1. Accuracy_score
2. Precision
3. Recall 
4. F1_score
5. Confusion Matrix

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('student_depression_dataset.csv')
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  object
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), object(9)
memory usage: 3.8+ MB

In [4]:
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

### Feature Selection

In [6]:
df=df[['Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'CGPA', 'Study Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression']]

In [9]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])
df["City"] = le.fit_transform(df["City"])
df["Profession"] = le.fit_transform(df["Profession"])
df["Dietary Habits"] = le.fit_transform(df["Dietary Habits"])
df["Sleep Duration"]= le.fit_transform(df["Sleep Duration"])
df["Family History of Mental Illness"] = le.fit_transform(df["Family History of Mental Illness"])

In [10]:
df.head()

,Gender,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,1,33.0,51,12,5.0,8.97,2.0,0,0,3.0,1.0,0,1
1,0,24.0,5,12,2.0,5.90,5.0,0,1,3.0,2.0,1,0
2,1,31.0,44,12,3.0,7.03,5.0,2,0,9.0,1.0,1,0
3,0,28.0,49,12,3.0,5.59,2.0,1,1,4.0,5.0,1,1
4,0,25.0,18,12,4.0,8.13,3.0,0,1,1.0,1.0,0,0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Gender                            27901 non-null  int64
 1   Age                               27901 non-null  float64
 2   City                              27901 non-null  int64
 3   Profession                        27901 non-null  int64
 4   Academic Pressure                 27901 non-null  float64
 5   CGPA                              27901 non-null  float64
 6   Study Satisfaction                27901 non-null  float64
 7   Sleep Duration                    27901 non-null  int64
 8   Dietary Habits                    27901 non-null  int64
 9   Work/Study Hours                  27901 non-null  float64
 10  Financial Stress                  27901 non-null  object
 11  Family History of Mental Illness  27901 non-null  int64
 12  Depression                        27901 non-null  int64
dtypes: float64(5), int64(7), object(1)
memory usage: 2.8+ MB

In [14]:
df=df[df["Financial Stress"]!='?'] # Removing rows with missing values in 'Financial Stress' column
df["Financial Stress"]=df["Financial Stress"].astype('float32')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27898 entries, 0 to 27900
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Gender                            27898 non-null  int64
 1   Age                               27898 non-null  float64
 2   City                              27898 non-null  int64
 3   Profession                        27898 non-null  int64
 4   Academic Pressure                 27898 non-null  float64
 5   CGPA                              27898 non-null  float64
 6   Study Satisfaction                27898 non-null  float64
 7   Sleep Duration                    27898 non-null  int64
 8   Dietary Habits                    27898 non-null  int64
 9   Work/Study Hours                  27898 non-null  float64
 10  Financial Stress                  27898 non-null  float32
 11  Family History of Mental Illness  27898 non-null  int64
 12  Depression                        27898 non-null  int64
dtypes: float32(1), float64(5), int64(7)
memory usage: 2.9 MB

### Sepearting I/P & O/P

In [16]:
X=df[['Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'CGPA', 'Study Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness']]
Y=df['Depression']

### Feature Scailing

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [18]:
X=scaler.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

### Logistic Regression

In [21]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression()

In [25]:
y_pred_lr=lr.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_lr = accuracy_score(Y_test, y_pred_lr)
print(f'Logistic Regression Accuracy: {accuracy_lr:.2f}')

Logistic Regression Accuracy: 0.79

### Decision Tree Classifier

In [49]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=5)
dt.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=5)

In [50]:
y_pred_dt=dt.predict(X_test)

In [51]:
accuracy_dt = accuracy_score(Y_test, y_pred_dt)
print(f'Decision Tree Accuracy: {accuracy_dt:.2f}')

Decision Tree Accuracy: 0.76

### Random Forest Classifier

In [52]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
rf.fit(X_train, Y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [53]:
y_pred_rf=rf.predict(X_test)

In [55]:
accuracy_rf=accuracy_score(Y_test, y_pred_rf)
print(f'Random Forest Accuracy: {accuracy_rf:.2f}')

Random Forest Accuracy: 0.78

### XGB Classifier, AdaBoost Classifer, CatBoost Classifier

In [57]:
from catboost import CatBoostClassifier
cb = CatBoostClassifier(iterations=100)
cb.fit(X_train, Y_train)

Learning rate set to 0.320487
0:	learn: 0.5993214	total: 24.1ms	remaining: 2.38s
1:	learn: 0.5444604	total: 35.4ms	remaining: 1.73s
2:	learn: 0.5077668	total: 42.9ms	remaining: 1.39s
3:	learn: 0.4870230	total: 51.4ms	remaining: 1.23s
4:	learn: 0.4713968	total: 57.4ms	remaining: 1.09s
5:	learn: 0.4611392	total: 63.5ms	remaining: 994ms
6:	learn: 0.4546050	total: 68ms	remaining: 903ms
7:	learn: 0.4500869	total: 73.6ms	remaining: 846ms
8:	learn: 0.4458677	total: 77.9ms	remaining: 788ms
9:	learn: 0.4427102	total: 82ms	remaining: 738ms
10:	learn: 0.4402059	total: 87.2ms	remaining: 706ms
11:	learn: 0.4380524	total: 92ms	remaining: 674ms
12:	learn: 0.4364574	total: 97.8ms	remaining: 654ms
13:	learn: 0.4351714	total: 103ms	remaining: 635ms
14:	learn: 0.4338194	total: 110ms	remaining: 621ms
15:	learn: 0.4325914	total: 114ms	remaining: 599ms
16:	learn: 0.4314109	total: 122ms	remaining: 596ms
17:	learn: 0.4306493	total: 127ms	remaining: 579ms
18:	learn: 0.4298066	total: 132ms	remaining: 561ms
19:	learn: 0.4290280	total: 138ms	remaining: 554ms
20:	learn: 0.4283116	total: 144ms	remaining: 542ms
21:	learn: 0.4277574	total: 149ms	remaining: 527ms
22:	learn: 0.4272265	total: 157ms	remaining: 525ms
23:	learn: 0.4269459	total: 161ms	remaining: 510ms
24:	learn: 0.4265343	total: 167ms	remaining: 502ms
25:	learn: 0.4262377	total: 173ms	remaining: 494ms
26:	learn: 0.4259293	total: 178ms	remaining: 481ms
27:	learn: 0.4254173	total: 184ms	remaining: 474ms
28:	learn: 0.4248528	total: 203ms	remaining: 497ms
29:	learn: 0.4241816	total: 208ms	remaining: 486ms
30:	learn: 0.4235261	total: 215ms	remaining: 479ms
31:	learn: 0.4231928	total: 220ms	remaining: 468ms
32:	learn: 0.4227449	total: 226ms	remaining: 458ms
33:	learn: 0.4221882	total: 231ms	remaining: 448ms
34:	learn: 0.4215164	total: 235ms	remaining: 437ms
35:	learn: 0.4211767	total: 240ms	remaining: 426ms
36:	learn: 0.4206972	total: 248ms	remaining: 422ms
37:	learn: 0.4205270	total: 253ms	remaining: 413ms
38:	learn: 0.4200243	total: 258ms	remaining: 403ms
39:	learn: 0.4196248	total: 278ms	remaining: 417ms
40:	learn: 0.4192280	total: 283ms	remaining: 407ms
41:	learn: 0.4185684	total: 294ms	remaining: 406ms
42:	learn: 0.4180938	total: 299ms	remaining: 397ms
43:	learn: 0.4177767	total: 305ms	remaining: 388ms
44:	learn: 0.4173050	total: 311ms	remaining: 380ms
45:	learn: 0.4168444	total: 316ms	remaining: 371ms
46:	learn: 0.4159894	total: 321ms	remaining: 362ms
47:	learn: 0.4155020	total: 329ms	remaining: 356ms
48:	learn: 0.4151486	total: 333ms	remaining: 347ms
49:	learn: 0.4149873	total: 342ms	remaining: 342ms
50:	learn: 0.4149431	total: 346ms	remaining: 332ms
51:	learn: 0.4146249	total: 352ms	remaining: 325ms
52:	learn: 0.4144354	total: 360ms	remaining: 320ms
53:	learn: 0.4139941	total: 367ms	remaining: 313ms
54:	learn: 0.4136751	total: 376ms	remaining: 308ms
55:	learn: 0.4133442	total: 381ms	remaining: 299ms
56:	learn: 0.4129105	total: 388ms	remaining: 293ms
57:	learn: 0.4125627	total: 396ms	remaining: 287ms
58:	learn: 0.4120896	total: 400ms	remaining: 278ms
59:	learn: 0.4117614	total: 409ms	remaining: 273ms
60:	learn: 0.4113613	total: 414ms	remaining: 265ms
61:	learn: 0.4108805	total: 422ms	remaining: 258ms
62:	learn: 0.4103379	total: 426ms	remaining: 250ms
63:	learn: 0.4098450	total: 433ms	remaining: 244ms
64:	learn: 0.4094014	total: 442ms	remaining: 238ms
65:	learn: 0.4089616	total: 451ms	remaining: 232ms
66:	learn: 0.4086338	total: 457ms	remaining: 225ms
67:	learn: 0.4082090	total: 461ms	remaining: 217ms
68:	learn: 0.4079043	total: 468ms	remaining: 210ms
69:	learn: 0.4076142	total: 473ms	remaining: 203ms
70:	learn: 0.4071551	total: 478ms	remaining: 195ms
71:	learn: 0.4070055	total: 485ms	remaining: 189ms
72:	learn: 0.4069844	total: 488ms	remaining: 181ms
73:	learn: 0.4064244	total: 493ms	remaining: 173ms
74:	learn: 0.4062127	total: 500ms	remaining: 167ms
75:	learn: 0.4058691	total: 505ms	remaining: 159ms
76:	learn: 0.4056452	total: 509ms	remaining: 152ms
77:	learn: 0.4051900	total: 515ms	remaining: 145ms
78:	learn: 0.4047952	total: 519ms	remaining: 138ms
79:	learn: 0.4045398	total: 524ms	remaining: 131ms
80:	learn: 0.4044324	total: 531ms	remaining: 125ms
81:	learn: 0.4041607	total: 535ms	remaining: 118ms
82:	learn: 0.4038290	total: 540ms	remaining: 111ms
83:	learn: 0.4035364	total: 547ms	remaining: 104ms
84:	learn: 0.4032312	total: 550ms	remaining: 97.1ms
85:	learn: 0.4029469	total: 554ms	remaining: 90.2ms
86:	learn: 0.4026189	total: 561ms	remaining: 83.9ms
87:	learn: 0.4020424	total: 565ms	remaining: 77.1ms
88:	learn: 0.4016481	total: 569ms	remaining: 70.4ms
89:	learn: 0.4013720	total: 575ms	remaining: 63.9ms
90:	learn: 0.4012371	total: 580ms	remaining: 57.4ms
91:	learn: 0.4007932	total: 584ms	remaining: 50.8ms
92:	learn: 0.4002213	total: 589ms	remaining: 44.3ms
93:	learn: 0.3996106	total: 597ms	remaining: 38.1ms
94:	learn: 0.3993283	total: 601ms	remaining: 31.6ms
95:	learn: 0.3990302	total: 607ms	remaining: 25.3ms
96:	learn: 0.3990096	total: 614ms	remaining: 19ms
97:	learn: 0.3987868	total: 620ms	remaining: 12.7ms
98:	learn: 0.3983704	total: 627ms	remaining: 6.34ms
99:	learn: 0.3981146	total: 631ms	remaining: 0us

In [58]:
y_pred_cb=cb.predict(X_test)
accuracy_cb=accuracy_score(Y_test, y_pred_cb)
print(f'CatBoost Classifier Accuracy: {accuracy_cb:.2f}')

CatBoost Classifier Accuracy: 0.80

In [59]:
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=100)
xgb.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [60]:
y_pred_xgb=xgb.predict(X_test)
accuracy_xgb=accuracy_score(Y_test, y_pred_xgb)
print(f'XGBoost Classifier Accuracy: {accuracy_xgb:.2f}')

XGBoost Classifier Accuracy: 0.79

In [61]:
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier(n_estimators=100)
adb.fit(X_train, Y_train)

AdaBoostClassifier(n_estimators=100)

In [62]:
y_pred_adb=adb.predict(X_test)
accuracy_adb=accuracy_score(Y_test, y_pred_adb)
print(f'AdaBoost Classifier Accuracy: {accuracy_adb:.2f}')

AdaBoost Classifier Accuracy: 0.80

### K-NN

In [63]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [64]:
y_pred_knn=knn.predict(X_test)
accuracy_knn=accuracy_score(Y_test, y_pred_knn)
print(f'K-Nearest Neighbors Accuracy: {accuracy_knn:.2f}')

K-Nearest Neighbors Accuracy: 0.76

### Support Vector Classifier

In [65]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train, Y_train)

SVC(kernel='linear')

In [66]:
y_pred_svc=svc.predict(X_test)
accuracy_svc=accuracy_score(Y_test, y_pred_svc)
print(f'Support Vector Machine Accuracy: {accuracy_svc:.2f}')

Support Vector Machine Accuracy: 0.79

### Naive Bayes ---> Bernoulli Naive Bayes, Multinomial Naive Bayes

In [67]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(X_train, Y_train)

BernoulliNB()

In [68]:
y_pred_nb=nb.predict(X_test)
accuracy_nb=accuracy_score(Y_test, y_pred_nb)
print(f'Naive Bayes Accuracy: {accuracy_nb:.2f}')

Naive Bayes Accuracy: 0.75

In [70]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train, Y_train) ### In this algo, we can't have negative values in X_train

ValueError: Negative values in data passed to MultinomialNB (input X).

### bagging Classifer

In [71]:
from sklearn.ensemble import BaggingClassifier
bagging = BaggingClassifier(n_estimators=100, random_state=42)
bagging.fit(X_train, Y_train)

BaggingClassifier(n_estimators=100, random_state=42)

In [72]:
y_pred_bagging=bagging.predict(X_test)
accuracy_bagging=accuracy_score(Y_test, y_pred_bagging)
print(f'Bagging Classifier Accuracy: {accuracy_bagging:.2f}')

Bagging Classifier Accuracy: 0.78

### Stacking Classifier

In [74]:
from sklearn.ensemble import StackingClassifier
estimators = [                ## Another way to do stacking ---> estimators=[
    ('rf', rf),                                          #       ('rf',RandomForestClassifier(),
    ('bagging', bagging)                                 #       ('bagging',BaggingClassifier())
]
stack=StackingClassifier(estimators=estimators, final_estimator=AdaBoostClassifier())
stack.fit(X_train, Y_train)

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(max_depth=5,
                                                       random_state=42)),
                               ('bagging',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=AdaBoostClassifier())

In [75]:
y_pred_stack=stack.predict(X_test)
accuracy_stack=accuracy_score(Y_test, y_pred_stack)
print(f'Stacking Classifier Accuracy: {accuracy_stack:.2f}')

Stacking Classifier Accuracy: 0.79

### Hyper Parameter Tuning ---> RandomSearchCV, GridSearchCV

In [76]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {'n_estimators': [100, 200, 300],'max_depth': [4, 6, 8]}
grid_search = GridSearchCV(estimator=RandomForestClassifier(),param_grid=param_grid,cv=5)
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [4, 6, 8],
                         'n_estimators': [100, 200, 300]})

In [78]:
grid_search.best_params_ #It will give best parameters found from the grid search

{'max_depth': 8, 'n_estimators': 200}

In [77]:
grid_search.best_score_ #It will give best score achieved during the grid search

np.float64(0.7959044276436202)

In [80]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {'n_estimators': [100, 200, 300],'max_depth': [4, 6, 8]}
randomcv=RandomizedSearchCV = RandomizedSearchCV(estimator=RandomForestClassifier(),param_distributions=param_grid,n_iter=10,cv=5)
randomcv.fit(X_train, Y_train)

C:\Users\Badal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'max_depth': [4, 6, 8],
                                        'n_estimators': [100, 200, 300]})

In [81]:
randomcv.best_params_

{'n_estimators': 200, 'max_depth': 8}

In [82]:
randomcv.best_score_

np.float64(0.795366702886417)

### TO convert model into a file

In [83]:
import pickle
with open('student_depression_model.pkl', 'wb') as f:
    pickle.dump(stack, f)

In [84]:
with open('student_depression_model.pkl', 'rb') as f:
    new_model = pickle.load(f)

In [85]:
new_model

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(max_depth=5,
                                                       random_state=42)),
                               ('bagging',
                                BaggingClassifier(n_estimators=100,
                                                  random_state=42))],
                   final_estimator=AdaBoostClassifier())